apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdig-agent
data:
  dragent.yaml: |
    ### Agent tags
     tags: cluster:Vikram-Sysdig_Test_Cluster,statefulset:yes

    # Sysdig collector address
     collector: kat.dev.draios.com

     #Collector TCP port
     collector_port: 6443

     #Whether collector accepts ssl
     ssl: true

    # collector certificate validation
     ssl_verify_certificate: false
     #log:
     #  file_priority: debug 
     new_k8s: true
     k8s_cluster_name: Vikram-SysdigTestCluster
     #percentiles: [50, 95, 99]
     app_checks_limit: 1000
     #metrics_excess_log: true
     prometheus:
       enabled: true
       interval: 10
       log_errors: true
       max_metrics: 3000
       max_metrics_per_process: 2000
       max_tags_per_metric: 200
       histograms: true
     jmx:
       limit: 3000
     statsd:
       limit: 1000
     app_checks_always_send: true
     
     security:
       k8s_audit_server_url: 0.0.0.0
       k8s_audit_server_port: 7765
       enabled: true
     commandlines_capture:
       enabled: true
     nmemdump:
       enabled: true
